name: Test and publish

on:
  release:
    types: [published]

jobs:
  publishToNuget:

    runs-on: ubuntu-latest

    env:
      tag: ${{ github.event.release.tag_name }}
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
        source-url: https://nuget.pkg.github.com/aeinbu/index.json
        owner: aeinbu
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_ORG_TOKEN}}

    - name: Build
      run: dotnet build Materializer --configuration Release --nologo

    - name: Run tests
      run: dotnet test Materializer.Tests

    - name: Pack
      run: dotnet pack Materializer --configuration Release -p:PackageVersion=${tag#?}

    - name: Publish NuGet
      run: dotnet nuget push Materializer/bin/Release/*.nupkg -k ${{secrets.NUGET_ORG_TOKEN}} -s https://api.nuget.org/v3/index.json
